import { auth } from "@/app/(auth)/auth";
import { streamText } from "ai";
import { myProvider } from "@/lib/ai/providers";
import { NextResponse } from "next/server";

const GUIDES = [
	{ name: "A Respectable Woman", number: 1 },
	{ name: "Teaching Critical Thinking", number: 2 },
	{ name: "The Corrections", number: 3 },
];

export async function POST(request: Request) {
	const session = await auth();

	if (!session?.user?.id) {
		return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
	}

	try {
		const { prompt, guide1Output, guide2Output, guide3Output } =
			await request.json();

		if (!prompt || !guide1Output || !guide2Output || !guide3Output) {
			return NextResponse.json(
				{ error: "Prompt and all three outputs are required" },
				{ status: 400 },
			);
		}

		const analysisPrompt = `You are evaluating lesson plan outputs generated by an AI model. Your task is to analyze how well each output followed the given prompt and provide detailed, constructive commentary.

**Original Prompt:**
${prompt}

**Guide 1 Output (${GUIDES[0].name}):**
${guide1Output}

**Guide 2 Output (${GUIDES[1].name}):**
${guide2Output}

**Guide 3 Output (${GUIDES[2].name}):**
${guide3Output}

**Your Analysis Should Include:**

1. **Overall Assessment** (2-3 sentences)
   - How well did the outputs follow the prompt structure overall?
   - Were there consistent patterns across all three outputs?

2. **Individual Scores** (Format: "Guide X: Y/10")
   - Score each guide's output from 1-10 on prompt adherence
   - Consider: completeness, structure, pedagogical quality, depth

3. **Strengths** (Bullet points)
   - What did the outputs do well?
   - Which aspects of the prompt were followed effectively?
   - Any particularly strong examples?

4. **Areas for Improvement** (Bullet points)
   - What was missing or could be better?
   - Which prompt requirements were not fully met?
   - Specific gaps or weaknesses

5. **Prompt Effectiveness**
   - Is the prompt clear and effective?
   - Should any part of the prompt be revised?
   - Suggestions for the next iteration

6. **Key Takeaways** (2-3 sentences)
   - Main insights from this test
   - Recommendations for next steps

**Format your response as clear, professional documentation suitable for a spreadsheet. Use markdown formatting (headers, bullets, bold) for readability.**`;

		// Stream the analysis
		const { textStream } = streamText({
			model: myProvider.languageModel("chat-model-claude"),
			prompt: analysisPrompt,
			temperature: 0.3, // Lower temperature for more consistent analysis
		});

		// Collect the full response
		let commentary = "";
		for await (const chunk of textStream) {
			commentary += chunk;
		}

		return NextResponse.json({
			success: true,
			commentary,
		});
	} catch (error: any) {
		console.error("Error analyzing outputs:", error);
		return NextResponse.json(
			{ error: "Failed to analyze outputs", details: error.message },
			{ status: 500 },
		);
	}
}
